GET http://localhost:3001/api/diagnoses HTTP/1.1

###

GET http://localhost:3001/api/patients HTTP/1.1

###

GET http://localhost:3001/api/patients/d2773598-f723-11e9-8f0b-362b9e155667 HTTP/1.1

###

POST http://localhost:3001/api/patients HTTP/1.1
content-type: application/json

{
  "name": "test",
  "dateOfBirth": "2020-01-01",
  "ssn": "test123",
  "gender": "male",
  "occupation": "cop"
}

###

POST http://localhost:3001/api/patients/d2773598-f723-11e9-8f0b-362b9e155667/entries HTTP/1.1
content-type: application/json

{
  "id": "b4f4eca1-2aa7-4b13-9a18-4a5535c3c8dassss",
  "date": "2023-10-20",
  "specialist": "Me",
  "type": "HealthCheck",
  "description": "testing",
  "healthCheckRating": 0
}

