GET http://localhost:3001/api/blogs HTTP/1.1

###

POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer XXXXXXXX

{
    "title": "wow",
    "author": "me",
    "url": "hehe.hehe",
    "likes": 20
}

###

DELETE http://localhost:3001/api/blogs/63a953e2309d983f755eef8d HTTP/1.1
Authorization: bearer XXXXXXXX
